name: papers
dependencies:
  - python==3.7.0
  - jupyter
  - scipy==1.1.0
  - pandas==0.23.4
  - matplotlib
  - seaborn==0.9.0
  #- scikit-learn==0.20.1
  #- statsmodels==0.9.0
  - spacy
  #- lxml
  #- html5lib
  - bs4
  #- tqdm
  - spyder-kernels==2.0.1
  - pip
  - pip:
    - PyYAML # yml files
    - arxiv
    - cleantext
    #- ray
